on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: lorismaz/github-hatchbox-deploy-action@v1
        with:
          deploy_key: ${{ secrets.HATCHBOX_DEPLOY_KEY }}
          branch: develop
